export interface NavLeaf {
  label: string;
  href: string;
  description?: string;
}

export interface NavColumn {
  title?: string;
  items: NavLeaf[];
}

export interface NavItem {
  label: string;
  href: string;
  columns?: NavColumn[];
}

const u = (slug: string) => `/universities/${slug}`;

export const navItems: NavItem[] = [
  {
    label: "Universities",
    href: "/universities",
    columns: [
      {
        title: "Popular destinations",
        items: [
          { label: "United Kingdom", href: u("uk") },
          { label: "United States", href: u("usa") },
          { label: "Canada", href: u("canada") },
          { label: "Australia", href: u("australia") },
          { label: "Germany", href: u("germany") },
          { label: "France", href: u("france") },
          { label: "Netherlands", href: u("netherlands") },
          { label: "Ireland", href: u("ireland") },
          { label: "New Zealand", href: u("new-zealand") },
          { label: "Switzerland", href: u("switzerland") },
          { label: "Sweden", href: u("sweden") },
          { label: "Italy", href: u("italy") },
          { label: "Spain", href: u("spain") },
          { label: "Japan", href: u("japan") },
          { label: "South Korea", href: u("south-korea") },
          { label: "Singapore", href: u("singapore") },
          { label: "United Arab Emirates", href: u("uae") },
          { label: "Malaysia", href: u("malaysia") },
          { label: "Norway", href: u("norway") },
          { label: "Denmark", href: u("denmark") },
        ],
      },
      {
        title: "By subject",
        items: [
          { label: "Engineering", href: u("engineering") },
          { label: "Business & Management", href: u("business") },
          { label: "Computer Science", href: u("computer-science") },
          { label: "Medicine", href: u("medicine") },
          { label: "Law", href: u("law") },
          { label: "Nursing", href: u("nursing") },
          { label: "Architecture", href: u("architecture") },
          { label: "Psychology", href: u("psychology") },
          { label: "Finance", href: u("finance") },
          { label: "Data Science", href: u("data-science") },
          { label: "Economics", href: u("economics") },
          { label: "Education", href: u("education") },
          { label: "Pharmacy", href: u("pharmacy") },
          { label: "Dentistry", href: u("dentistry") },
          { label: "Mechanical Engineering", href: u("mechanical-engineering") },
          { label: "Electrical Engineering", href: u("electrical-engineering") },
          { label: "Civil Engineering", href: u("civil-engineering") },
          { label: "Accounting", href: u("accounting") },
          { label: "Marketing", href: u("marketing") },
          { label: "International Relations", href: u("international-relations") },
        ],
      },
      {
        title: "By degree level",
        items: [
          { label: "Foundation", href: u("foundation") },
          { label: "Diploma", href: u("diploma") },
          { label: "Advanced Diploma", href: u("advanced-diploma") },
          { label: "Bachelor's degrees", href: u("bachelors") },
          { label: "Bachelor's (Hons)", href: u("bachelors-hons") },
          { label: "Postgraduate Certificate", href: u("pg-certificate") },
          { label: "Postgraduate Diploma", href: u("pg-diploma") },
          { label: "Master's degrees", href: u("masters") },
          { label: "MBA", href: u("mba") },
          { label: "Executive MBA", href: u("executive-mba") },
          { label: "MPhil", href: u("mphil") },
          { label: "PhD", href: u("phd") },
          { label: "Doctorate", href: u("doctorate") },
          { label: "Pre-Master's", href: u("pre-masters") },
          { label: "Pre-PhD", href: u("pre-phd") },
          { label: "Short courses", href: u("short-courses") },
          { label: "Summer school", href: u("summer-school") },
          { label: "Online degrees", href: u("online-degrees") },
          { label: "Part-time study", href: u("part-time") },
          { label: "Research programs", href: u("research") },
        ],
      },
      {
        title: "Top universities",
        items: [
          { label: "University of Oxford", href: u("oxford") },
          { label: "University of Cambridge", href: u("cambridge") },
          { label: "Imperial College London", href: u("imperial-college-london") },
          { label: "University College London", href: u("ucl") },
          { label: "University of Edinburgh", href: u("edinburgh") },
          { label: "MIT", href: u("mit") },
          { label: "Stanford University", href: u("stanford") },
          { label: "Harvard University", href: u("harvard") },
          { label: "Caltech", href: u("caltech") },
          { label: "University of Chicago", href: u("chicago") },
          { label: "ETH Zurich", href: u("eth-zurich") },
          { label: "EPFL", href: u("epfl") },
          { label: "University of Toronto", href: u("toronto") },
          { label: "University of Melbourne", href: u("melbourne") },
          { label: "University of Sydney", href: u("sydney") },
          { label: "National University of Singapore", href: u("nus") },
          { label: "Nanyang Technological University", href: u("ntu") },
          { label: "University of Tokyo", href: u("tokyo") },
          { label: "Kyoto University", href: u("kyoto") },
          { label: "Sorbonne University", href: u("sorbonne") },
        ],
      },
      {
        title: "Europe",
        items: [
          { label: "United Kingdom", href: u("uk") },
          { label: "Germany", href: u("germany") },
          { label: "France", href: u("france") },
          { label: "Netherlands", href: u("netherlands") },
          { label: "Ireland", href: u("ireland") },
          { label: "Switzerland", href: u("switzerland") },
          { label: "Sweden", href: u("sweden") },
          { label: "Norway", href: u("norway") },
          { label: "Denmark", href: u("denmark") },
          { label: "Finland", href: u("finland") },
          { label: "Italy", href: u("italy") },
          { label: "Spain", href: u("spain") },
          { label: "Austria", href: u("austria") },
          { label: "Belgium", href: u("belgium") },
          { label: "Poland", href: u("poland") },
          { label: "Portugal", href: u("portugal") },
          { label: "Czech Republic", href: u("czech-republic") },
          { label: "Hungary", href: u("hungary") },
          { label: "Greece", href: u("greece") },
          { label: "Turkey", href: u("turkey") },
        ],
      },
      {
        title: "Asia",
        items: [
          { label: "China", href: u("china") },
          { label: "Japan", href: u("japan") },
          { label: "South Korea", href: u("south-korea") },
          { label: "Singapore", href: u("singapore") },
          { label: "Malaysia", href: u("malaysia") },
          { label: "India", href: u("india") },
          { label: "Thailand", href: u("thailand") },
          { label: "Vietnam", href: u("vietnam") },
          { label: "Indonesia", href: u("indonesia") },
          { label: "Philippines", href: u("philippines") },
          { label: "Hong Kong", href: u("hong-kong") },
          { label: "Taiwan", href: u("taiwan") },
          { label: "United Arab Emirates", href: u("uae") },
          { label: "Saudi Arabia", href: u("saudi-arabia") },
          { label: "Qatar", href: u("qatar") },
          { label: "Kazakhstan", href: u("kazakhstan") },
          { label: "Sri Lanka", href: u("sri-lanka") },
          { label: "Nepal", href: u("nepal") },
          { label: "Bangladesh", href: u("bangladesh") },
          { label: "Pakistan", href: u("pakistan") },
        ],
      },
      {
        title: "Americas & Oceania",
        items: [
          { label: "United States", href: u("usa") },
          { label: "Canada", href: u("canada") },
          { label: "Mexico", href: u("mexico") },
          { label: "Brazil", href: u("brazil") },
          { label: "Argentina", href: u("argentina") },
          { label: "Chile", href: u("chile") },
          { label: "Colombia", href: u("colombia") },
          { label: "Peru", href: u("peru") },
          { label: "Costa Rica", href: u("costa-rica") },
          { label: "Cuba", href: u("cuba") },
          { label: "Australia", href: u("australia") },
          { label: "New Zealand", href: u("new-zealand") },
          { label: "Fiji", href: u("fiji") },
          { label: "Jamaica", href: u("jamaica") },
          { label: "Ecuador", href: u("ecuador") },
          { label: "Uruguay", href: u("uruguay") },
          { label: "Bolivia", href: u("bolivia") },
          { label: "Panama", href: u("panama") },
          { label: "Dominican Republic", href: u("dominican-republic") },
          { label: "Puerto Rico", href: u("puerto-rico") },
        ],
      },
      {
        title: "By study area",
        items: [
          { label: "STEM", href: u("stem") },
          { label: "Health Sciences", href: u("health-sciences") },
          { label: "Business", href: u("business-area") },
          { label: "Humanities", href: u("humanities") },
          { label: "Social Sciences", href: u("social-sciences") },
          { label: "Arts & Design", href: u("arts-design") },
          { label: "Education", href: u("education-area") },
          { label: "Law & Legal Studies", href: u("law-legal") },
          { label: "Agriculture", href: u("agriculture") },
          { label: "Environmental Studies", href: u("environmental-studies") },
          { label: "Media & Communication", href: u("media-communication") },
          { label: "Hospitality & Tourism", href: u("hospitality-tourism") },
          { label: "Sports Science", href: u("sports-science") },
          { label: "Aviation", href: u("aviation") },
          { label: "Marine Studies", href: u("marine-studies") },
          { label: "Fashion", href: u("fashion") },
          { label: "Music", href: u("music") },
          { label: "Performing Arts", href: u("performing-arts") },
          { label: "Theology", href: u("theology") },
          { label: "Public Administration", href: u("public-administration") },
        ],
      },
      {
        title: "By city",
        items: [
          { label: "London", href: u("city-london") },
          { label: "Manchester", href: u("city-manchester") },
          { label: "Edinburgh", href: u("city-edinburgh") },
          { label: "New York", href: u("city-new-york") },
          { label: "Boston", href: u("city-boston") },
          { label: "Los Angeles", href: u("city-los-angeles") },
          { label: "Chicago", href: u("city-chicago") },
          { label: "Toronto", href: u("city-toronto") },
          { label: "Vancouver", href: u("city-vancouver") },
          { label: "Sydney", href: u("city-sydney") },
          { label: "Melbourne", href: u("city-melbourne") },
          { label: "Berlin", href: u("city-berlin") },
          { label: "Munich", href: u("city-munich") },
          { label: "Paris", href: u("city-paris") },
          { label: "Amsterdam", href: u("city-amsterdam") },
          { label: "Dublin", href: u("city-dublin") },
          { label: "Zurich", href: u("city-zurich") },
          { label: "Singapore", href: u("city-singapore") },
          { label: "Hong Kong", href: u("city-hong-kong") },
          { label: "Tokyo", href: u("city-tokyo") },
        ],
      },
      {
        title: "Resources",
        items: [
          { label: "Top universities", href: "/universities/top" },
          { label: "University rankings", href: "/rankings" },
          { label: "Compare universities", href: "/compare" },
          { label: "Study guides", href: "/guides" },
          { label: "Admission requirements", href: "/guides/admission" },
          { label: "Tuition fees", href: "/guides/tuition-fees" },
          { label: "Scholarships", href: "/scholarships" },
          { label: "Student visas", href: "/guides/visa" },
          { label: "Cost of living", href: "/guides/cost-of-living" },
          { label: "Accommodation", href: "/guides/accommodation" },
          { label: "Application deadlines", href: "/guides/deadlines" },
          { label: "Language requirements", href: "/guides/language-requirements" },
          { label: "IELTS & TOEFL", href: "/guides/ielts" },
          { label: "Student life", href: "/guides/student-life" },
          { label: "Career prospects", href: "/guides/careers" },
          { label: "Internships", href: "/guides/internships" },
          { label: "Exchange programs", href: "/guides/exchange" },
          { label: "Open days", href: "/guides/open-days" },
          { label: "Free counselling", href: "/guides/counselling" },
          { label: "FAQs", href: "/guides/faqs" },
        ],
      },
    ],
  },
  {
    label: "Programs",
    href: "/programs",
    columns: [
      {
        title: "Study level",
        items: [
          { label: "Bachelor's degrees", href: "/programs/bachelors" },
          { label: "Master's degrees", href: "/programs/masters" },
          { label: "PhD & research", href: "/programs/phd" },
          { label: "MBA", href: "/programs/mba" },
          { label: "Foundation programs", href: "/programs/foundation" },
        ],
      },
      {
        title: "Popular fields",
        items: [
          { label: "Data Science", href: "/programs/data-science" },
          { label: "Nursing", href: "/programs/nursing" },
          { label: "Architecture", href: "/programs/architecture" },
          { label: "Psychology", href: "/programs/psychology" },
          { label: "Finance", href: "/programs/finance" },
        ],
      },
      {
        title: "Resources",
        items: [
          { label: "Program guides", href: "/guides/programs" },
          { label: "Entry requirements", href: "/guides/entry-requirements" },
          { label: "Tuition fees", href: "/guides/tuition-fees" },
        ],
      },
    ],
  },
  {
    label: "Rankings",
    href: "/rankings",
    columns: [
      {
        title: "Ranking publishers",
        items: [
          { label: "QS World University Rankings", href: "/rankings/qs" },
          { label: "Times Higher Education", href: "/rankings/the" },
          { label: "Academic Ranking (ARWU)", href: "/rankings/arwu" },
          { label: "U.S. News Best Global", href: "/rankings/us-news" },
        ],
      },
    ],
  },
  {
    label: "Study destinations",
    href: "/destinations",
    columns: [
      {
        title: "By country",
        items: [
          { label: "United Kingdom", href: "/destinations/uk" },
          { label: "United States", href: "/destinations/usa" },
          { label: "Canada", href: "/destinations/canada" },
          { label: "Australia", href: "/destinations/australia" },
        ],
      },
      {
        title: "More countries",
        items: [
          { label: "Germany", href: "/destinations/germany" },
          { label: "Netherlands", href: "/destinations/netherlands" },
          { label: "Ireland", href: "/destinations/ireland" },
          { label: "New Zealand", href: "/destinations/new-zealand" },
        ],
      },
    ],
  },
  {
    label: "Scholarships",
    href: "/scholarships",
    columns: [
      {
        title: "By level",
        items: [
          { label: "Undergraduate scholarships", href: "/scholarships/undergraduate" },
          { label: "Postgraduate scholarships", href: "/scholarships/postgraduate" },
          { label: "PhD funding", href: "/scholarships/phd" },
        ],
      },
      {
        title: "By type",
        items: [
          { label: "Government scholarships", href: "/scholarships/government" },
          { label: "University scholarships", href: "/scholarships/university" },
          { label: "Country-specific", href: "/scholarships/countries" },
        ],
      },
    ],
  },
  {
    label: "Guides",
    href: "/guides",
    columns: [
      {
        title: "Applying",
        items: [
          { label: "Application guide", href: "/guides/application" },
          { label: "Statement of purpose", href: "/guides/statement-of-purpose" },
          { label: "Visa guide", href: "/guides/visa" },
        ],
      },
      {
        title: "Tests & prep",
        items: [
          { label: "IELTS", href: "/guides/ielts" },
          { label: "TOEFL", href: "/guides/toefl" },
          { label: "GRE & GMAT", href: "/guides/gre-gmat" },
        ],
      },
    ],
  },
  {
    label: "Compare",
    href: "/compare",
  },
];
